#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

$dotenv = Dotenv\Dotenv::createImmutable(__DIR__ );
$dotenv->load();

const MIGRATIONS_PATH = __DIR__."/migrations";

$migrate = new class {
    public function exec(): void
    {
        $this->runMigrations();
    }

    private function runMigrations(): void
    {
        $files = glob(MIGRATIONS_PATH.'/*.php');
        $this->run($files);
    }

    private function run($files): void
    {
        foreach ($files as $file) {
            (require $file)();
        }
    }
};

$migrate->exec();
